version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/src/
    container_name: mockserver_client_dev
    working_dir: /src
    env_file:
      - docker.env

  mock-server:
    image: mockserver/mockserver:5.15.0
    entrypoint: [
      "java",
      "-Dfile.encoding=UTF-8",
      "-cp",
      "/mockserver-netty-jar-with-dependencies.jar:/libs/*",
      "-Dmockserver.propertyFile=/config/mockserver.properties",
      "-Dmockserver.logLevel=DEBUG",
      "-Dmockserver.maxChunkSize=2",
      "org.mockserver.cli.Main"
    ]
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_LIVENESS_HTTP_GET_PATH=/health
      - MOCKSERVER_MAX_CHUNK_SIZE=2
