version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/src/
    container_name: mockserver_client_dev
    working_dir: /src
    env_file:
      - docker.env

  mock-server:
    image: mockserver/mockserver:mockserver-5.15.0
    command: -serverPort 1080
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_LIVENESS_HTTP_GET_PATH=/health
